require("modules.env")

hl.on("hyprland.start", function()
  hl.exec_cmd("terminal")
  hl.exec_cmd("waybar")
  hl.exec_cmd("swaync")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("fcitx5")
  hl.exec_cmd("vicinae server")
  hl.exec_cmd("cd /home/annguyen/.config/hypr/scripts && ./theme-switch.sh auto")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("snappy-switcher --daemon")
  hl.exec_cmd("swayosd-server")
  hl.exec_cmd("mpris-proxy")
end)
