# import source
source = ~/.config/hypr/modules/binds.conf
source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/windows.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/appearance.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/mics.conf

# HyprMod managed settings
# source = /home/annguyen/.config/hypr/hyprland-gui.conf
