### AUTOSTART ###
exec-once = $terminal
exec-once = waybar
exec-once = awww-daemon
#exec-once = cd ~/.local/bin && ./walset.sh /home/annguyen/Pictures/Wallpapers/dark 1800
exec-once = swaync
exec-once = hypridle
exec-once = fcitx5
exec-once = systemctl --user start hyprpolkitagent
exec-once = vicinae server
exec-once = snappy-switcher --daemon
#exec-once = swayosd-server
